//Autogenerated Static Lib File:
//Generated on: 06/30/13 12:17:14


#include "./StaticLibSymbols.h"
#ifdef _LIB


void *GLRENDERER_LIBEXTERNS[] = {
	(void *)&CMoviePlayerRO,
	(void *)&CGLRendererRO,
	(void *)&CHModelManagerRO,
	(void *)&CGLCubeTextureObjectRO,
	(void *)&CMoviePlayerRO,
	(void *)&CPixelShaderRO,
	(void *)&CGLRendererRO,
	(void *)&CGLTextureObjectRO,
	(void *)&CVertexShaderRO,
	(void *)&CHModelManagerRO,
	(void *)&PlayMovie_CMoviePlayerRM,
	(void *)&StopMovie_CMoviePlayerRM,
	(void *)&PauseMovie_CMoviePlayerRM,
	(void *)&SetMovieVolume_CMoviePlayerRM,
	(void *)&IsMovieDone_CMoviePlayerRM,
	(void *)&DestroyRenderer_CMoviePlayerRM,
	(void *)&GetRendererInterface_CGLRendererRM,
	(void *)&SetDirectories_CGLRendererRM,
	(void *)&GetRayFromMouseCoords_CGLRendererRM,
	(void *)&TransformWorldToScreen_CGLRendererRM,
	(void *)0
};

#endif	//#ifdef _LIB

