//Autogenerated Static Lib File:
//Generated on: 06/30/13 12:17:14

#ifndef INCLUDE_SYMBOLS_GLRENDERER
#define INCLUDE_SYMBOLS_GLRENDERER
#endif	//#ifndef INCLUDE_SYMBOLS_GLRENDERER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *GLRENDERER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CMoviePlayerRO;
extern "C" CRegisterComponent CGLRendererRO;
extern "C" CRegisterComponent CHModelManagerRO;
//Component externs
extern "C" CRegisterComponent CGLCubeTextureObjectRO;
extern "C" CRegisterComponent CMoviePlayerRO;
extern "C" CRegisterComponent CPixelShaderRO;
extern "C" CRegisterComponent CGLRendererRO;
extern "C" CRegisterComponent CGLTextureObjectRO;
extern "C" CRegisterComponent CVertexShaderRO;
extern "C" CRegisterComponent CHModelManagerRO;
//Message externs
extern "C" CRegisterMessage PlayMovie_CMoviePlayerRM;
extern "C" CRegisterMessage StopMovie_CMoviePlayerRM;
extern "C" CRegisterMessage PauseMovie_CMoviePlayerRM;
extern "C" CRegisterMessage SetMovieVolume_CMoviePlayerRM;
extern "C" CRegisterMessage IsMovieDone_CMoviePlayerRM;
extern "C" CRegisterMessage DestroyRenderer_CMoviePlayerRM;
extern "C" CRegisterMessage GetRendererInterface_CGLRendererRM;
extern "C" CRegisterMessage SetDirectories_CGLRendererRM;
extern "C" CRegisterMessage GetRayFromMouseCoords_CGLRendererRM;
extern "C" CRegisterMessage TransformWorldToScreen_CGLRendererRM;

#endif	//#ifdef _LIB
