//Autogenerated Static Lib File:
//Generated on: 07/05/13 23:46:00


#include "./StaticLibSymbols.h"
#ifdef _LIB


void *TEXTURELOADER_LIBEXTERNS[] = {
	(void *)&CTextureLoaderRO,
	(void *)&CTextureLoaderRO,
	(void *)&LoadFile_CTextureLoaderRM,
	(void *)&SaveFile_CTextureLoaderRM,
	(void *)&UnloadFile_CTextureLoaderRM,
	(void *)&SetSaveAsFormat_CTextureLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

