//Autogenerated Static Lib File:
//Generated on: 07/05/13 23:46:00

#ifndef INCLUDE_SYMBOLS_TEXTURELOADER
#define INCLUDE_SYMBOLS_TEXTURELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_TEXTURELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *TEXTURELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CTextureLoaderRO;
//Component externs
extern "C" CRegisterComponent CTextureLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CTextureLoaderRM;
extern "C" CRegisterMessage SaveFile_CTextureLoaderRM;
extern "C" CRegisterMessage UnloadFile_CTextureLoaderRM;
extern "C" CRegisterMessage SetSaveAsFormat_CTextureLoaderRM;

#endif	//#ifdef _LIB
