//Autogenerated Static Lib File:
//Generated on: 05/19/13 19:31:27


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LOADSAVEMANAGER_LIBEXTERNS[] = {
	(void *)&CLoadSaveManagerRO,
	(void *)&CLoadSaveManagerRO,
	(void *)&LoadFileByExtension_CLoadSaveManagerRM,
	(void *)&SaveFileByExtension_CLoadSaveManagerRM,
	(void *)&UnloadFileByExtension_CLoadSaveManagerRM,
	(void *)&RegisterLoadSaveComponent_CLoadSaveManagerRM,
	(void *)&GetFilterStrings_CLoadSaveManagerRM,
	(void *)&GetFileVersion_CLoadSaveManagerRM,
	(void *)&SetFileVersion_CLoadSaveManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

