//Autogenerated Static Lib File:
//Generated on: 06/08/13 16:57:21


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *OPENAL_LIBEXTERNS[] = {
	(void *)&COpenALSoundUtilityRO,
	(void *)&CMusicPlaylistRO,
	(void *)&COpenALSoundObjectRO,
	(void *)&COpenALSoundUtilityRO,
	(void *)&PlaySoundObject_CSoundObjectRM,
	(void *)&StopSoundObject_CSoundObjectRM,
	(void *)&AddSound_COpenALSoundUtilityRM,
	(void *)&SetListenerVectors_COpenALSoundUtilityRM,
	(void *)&GetSoundFileInfo_COpenALSoundUtilityRM,
	(void *)&ShutDownAudioEngine_COpenALSoundUtilityRM,
	(void *)&LoadSoundDatabase_COpenALSoundUtilityRM,
	(void *)&SetAudioBufferLength_COpenALSoundUtilityRM,
	(void *)&SetAudioBufferCount_COpenALSoundUtilityRM,
	(void *)&SetSoundScale_COpenALSoundUtilityRM,
	(void *)&SetGlobalAttenuationMultiplier_COpenALSoundUtilityRM,
	(void *)&SetGlobalDopplerFactor_COpenALSoundUtilityRM,
	(void *)&UpdateAudioEngine_COpenALSoundUtilityRM,
	(void *)0
};

#endif	//#ifdef _LIB

