//Autogenerated Static Lib File:
//Generated on: 06/30/13 12:17:17

#ifndef INCLUDE_SYMBOLS_SOUNDLOADER
#define INCLUDE_SYMBOLS_SOUNDLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_SOUNDLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SOUNDLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CSoundLoaderRO;
//Component externs
extern "C" CRegisterComponent CSoundLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CSoundLoaderRM;
extern "C" CRegisterMessage SaveFile_CSoundLoaderRM;

#endif	//#ifdef _LIB
