//Autogenerated Static Lib File:
//Generated on: 07/05/13 23:46:00


#include "./StaticLibSymbols.h"
#ifdef _LIB


void *SOUNDLOADER_LIBEXTERNS[] = {
	(void *)&CSoundLoaderRO,
	(void *)&CSoundLoaderRO,
	(void *)&LoadFile_CSoundLoaderRM,
	(void *)&SaveFile_CSoundLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

