//Autogenerated Static Lib File:
//Generated on: 06/08/13 16:57:30


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SOUNDLOADER_LIBEXTERNS[] = {
	(void *)&CSoundLoaderRO,
	(void *)&CSoundLoaderRO,
	(void *)&LoadFile_CSoundLoaderRM,
	(void *)&SaveFile_CSoundLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

